DesafioHackathon/Models/Carta.cs
namespace DesafioHackathon.Models
{
    public class Carta
    {
        public int Id { get; set; }

        public string Nome { get; set; }
        public int Numero { get; set; }
        public string Endere { get; set; }
        public string Dest { get; set; }
        public string Remet { get; set; }      
        public string Mensagem { get; set; }
    }
}

DesafioHackathon/Models/CartaContext.cs
using Microsoft.EntityFrameworkCore;

namespace DesafioHackathon.Models
{
    public class CartaContext : DbContext
    {
        public CartaContext(DbContextOptions<CartaContext> options) : base(options)
        {
        }
        public DbSet<Carta> Carta { get; set; }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            //builder.ApplyConfiguration(new CartaMap());
            builder.Entity<Carta>().HasKey(m => m.Id);
            base.OnModelCreating(builder);
        }
    }
}

DesafioHackathon/Models/CartaRepository.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioHackathon.Models
{
    public class CartaRepository
    {
        private readonly CartaContext _cartaContext;

        public CartaRepository(CartaContext cartaContext)
        {
            _cartaContext = cartaContext;
        }

        public async Task<IEnumerable<Carta>> ObterCarta()
        {
            return await _cartaContext.Carta.ToListAsync();
        }
    }
}

DesafioHackathon/Models/ErrorViewModel.cs
using System;

namespace DesafioHackathon.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DesafioHackathon/Controllers/CartaController.cs
using DesafioHackathon.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace DesafioHackathon.Controllers
{
    public class CartaController : Controller
    {
        private readonly CartaContext _context;

        public CartaController(CartaContext context)
        {
            _context = context;
        }


        private readonly string _Url = string.Format("https://localhost:44309");
        private readonly string _UrlApi = string.Format("/api/CartaService/");

        // GET: Carta
        public async Task<ActionResult> Index()
        {
            return View(await _context.Carta.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carta = await _context.Carta
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carta== null)
            {
                return NotFound();
            }

            return View(carta);
        }

        // GET: Contatos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cartas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Numero,Endere,Dest,Remet,Mensagem")] Carta carta
            )
        {
            if (ModelState.IsValid)
            {
                _context.Add(carta);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(carta);
        }

        

        // GET: Carta/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Carta/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Carta/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Carta/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DesafioHackathon/Controllers/CartaServiceController.cs
using DesafioHackathon.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace DesafioHackathon.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CartaServiceController : ControllerBase
    {
       

        //GET: api/CartaService
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }


        // GET: api/CartaService/5
        [HttpGet("{id}", Name = "Get")]
        public int Get(int id)
        {
            return id;
        }

        // POST: api/CartaService
        [HttpPost]
        public void Post(Carta carta)
        {

        }

        // PUT: api/CartaService/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE: api/ApiWithActions/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

DesafioHackathon/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DesafioHackathon.Models;

namespace DesafioHackathon.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesafioHackathon/Views/Carta/Create.cshtml
@model DesafioHackathon.Models.Carta

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Carta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endere" class="control-label"></label>
                <input asp-for="Endere" class="form-control" />
                <span asp-validation-for="Endere" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dest" class="control-label"></label>
                <input asp-for="Dest" class="form-control" />
                <span asp-validation-for="Dest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Remet" class="control-label"></label>
                <input asp-for="Remet" class="form-control" />
                <span asp-validation-for="Remet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mensagem" class="control-label"></label>
                <input asp-for="Mensagem" class="form-control" />
                <span asp-validation-for="Mensagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DesafioHackathon/Views/Carta/Filter.cshtml
@model DesafioHackathon.Models.Carta

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Carta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />

                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endere" class="control-label"></label>
                <input asp-for="Endere" class="form-control" />
                <span asp-validation-for="Endere" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dest" class="control-label"></label>
                <input asp-for="Dest" class="form-control" />
                <span asp-validation-for="Dest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Remet" class="control-label"></label>
                <input asp-for="Remet" class="form-control" />
                <span asp-validation-for="Remet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mensagem" class="control-label"></label>
                <input asp-for="Mensagem" class="form-control" />
                <span asp-validation-for="Mensagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DesafioHackathon/Views/Carta/Index.cshtml
@model IEnumerable<DesafioHackathon.Models.Carta>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Criar Novo Contato</a> <br />
    <a asp-action="Filter">Filtro</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endere)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Numero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dest)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Remet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mensagem)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model != null)
            {

                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Endere)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Numero)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Dest)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Remet)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mensagem)
                        </td>

                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>

DesafioHackathon/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo ao Desafio Hackathon 2020</h1>
</div>

DesafioHackathon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesafioHackathon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesafioHackathon</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carta" asp-action="Index">Carta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DesafioHackathon - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>